[build-system]
requires = [
    "setuptools>=46.4.0",
    "wheel",
    "Cython>=0.29.21,<3.0",
    'numpy==1.21.4',
    "dimod==0.11.0",
    "dwave_networkx>=0.7.0,<0.9.0",
]
build-backend = "setuptools.build_meta"
