[build-system]
requires = [
    "setuptools>=46.4.0",
    "wheel",
    "Cython>=0.29.21,<3.0",
    'numpy==1.19.5;python_version<"3.10"',
    'numpy==1.21.4;python_version>="3.10"',
    "dimod>=0.8.0,<0.11.0",
    "dwave_networkx>=0.7.0,<0.9.0",
]
build-backend = "setuptools.build_meta"
