[build-system]
requires = [
    "setuptools>=42.0.0",       # PEP-420 support, PEP-517/518 support
    "wheel>=0.30.0",            # limited python api support
    "cython>=0.29.23,<3.0",
    "numpy==1.19.4",
]
build-backend = "setuptools.build_meta"
