version: 2.1

orbs:
  win: circleci/windows@2.2.0
  ocean: dwave/ocean@dev:fee3dc9

parameters:
  xcode:
    type: string
    default: "12.3.0"

environment:
  PIP_PROGRESS_BAR: off

jobs:

  #
  # linux
  #

  build-manylinux:
    parameters:
      manylinux-tag:
        type: string
      manylinux-arch:
        type: string
      python-version:
        type: string

    docker:
      - image: quay.io/pypa/<< parameters.manylinux-tag >>_<< parameters.manylinux-arch >>

    steps:
      - checkout

      - run:
          name: Build wheels
          command: |
            for py in /opt/python/cp*/bin/python; do
              ver=$("$py" -c 'import sys; print("{0.major}.{0.minor}".format(sys.version_info))')
              req=<< parameters.python-version >>
              [[ "$ver" != "${req:0:3}" ]] && continue
              "$py" -m pip wheel . -w ./wheelhouse --no-deps
            done

      - run:
          name: Bundle shared libraries into wheels
          command: |
            plat="<< parameters.manylinux-tag >>_<< parameters.manylinux-arch >>"
            for whl in ./wheelhouse/*.whl; do
              auditwheel repair "$whl" --plat "$plat" -w ./distotheque
            done

      - store_artifacts: &store-dist
          path: distotheque

      - persist_to_workspace: &persist-dist
          root: distotheque
          paths: .

  build-sdist:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      - ocean/pip-install:
          requirements: requirements.txt
          cache: false

      - ocean/build-dist:
          dist-type: sdist
          dist-dir: ./distotheque

      - store_artifacts: *store-dist

      - persist_to_workspace: *persist-dist

  test-linux:
    parameters:
      python-version:
        type: string

    docker:
      - image: circleci/python:<< parameters.python-version >>

    steps:
      - checkout

      - attach_workspace: &attach-dist
          at: distotheque

      - ocean/install-requirements

      - ocean/pip-install:
          args: --no-index --find-links=distotheque dwave-greedy

      - ocean/coverage-run-unittest:
          upload-coverage: true

      - run: &run-cpp-tests
          name: Run C++ tests
          command: |
            . env/bin/activate
            make -C tests/ smoke

  test-install:
    docker:
      - image: circleci/python:3.7    # last version pip==8.1.0 works on

    steps:
      - checkout

      - attach_workspace: *attach-dist

      - run:
          # pip 10.0 is the first to support pyproject.toml build config
          name: Install from sdist with pip==10.0
          command: |
            python -m venv env-sdist-pip10
            . env-sdist-pip10/bin/activate
            pip install 'pip==10.0'
            pip install ./distotheque/dwave-greedy*.tar.gz

      - run:
          name: Install from sdist with latest pip
          command: |
            python -m venv env-sdist
            . env-sdist/bin/activate
            pip install -U pip
            pip install ./distotheque/dwave-greedy*.tar.gz

      - run:
          # pip 8.1.0 is the first version that supports manylinux1
          name: Install from wheel with pip==8.1.0
          command: |
            python -m venv env-wheel-pip8
            . env-wheel-pip8/bin/activate
            pip install 'pip==8.1.0'
            # TODO: can we search for package locally, but install deps from pypi?
            pip install -r requirements.txt
            pip install --no-index --find-links=distotheque --only-binary=dwave-greedy dwave-greedy

      - run:
          name: Install from wheel with latest pip
          command: |
            python -m venv env-wheel
            . env-wheel/bin/activate
            pip install -U pip
            pip install -r requirements.txt
            pip install --no-index --find-links=distotheque --only-binary=dwave-greedy dwave-greedy

  #
  # macos
  #

  build-macos:
    parameters:
      python-version:
        type: string
      xcode:
        type: string
        default: << pipeline.parameters.xcode >>

    macos:
      xcode: << parameters.xcode >>

    environment:
      # Force (lie about) macOS 10.9 binary compatibility.
      # Needed for properly versioned wheels.
      # See: https://github.com/MacPython/wiki/wiki/Spinning-wheels
      MACOSX_DEPLOYMENT_TARGET: 10.9

    steps:
      - checkout

      - ocean/brew-install-pyenv

      - ocean/pyenv-install-python:
          python-version: << parameters.python-version >>
          cache-key-prefix: << parameters.xcode >>

      - ocean/pip-install:
          requirements: requirements.txt
          cache: false

      - ocean/build-dist:
          dist-type: bdist_wheel
          dist-dir: ./distotheque

      - store_artifacts: *store-dist

      - persist_to_workspace: *persist-dist

  test-macos:
    parameters:
      python-version:
        type: string
      xcode:
        type: string
        default: << pipeline.parameters.xcode >>

    macos:
      xcode: << parameters.xcode >>

    steps:
      - checkout

      - ocean/brew-install-pyenv

      - ocean/pyenv-install-python:
          python-version: << parameters.python-version >>
          cache-key-prefix: << parameters.xcode >>

      - attach_workspace: *attach-dist

      - ocean/install-requirements

      - ocean/pip-install:
          args: --no-index --find-links=distotheque dwave-greedy

      - ocean/coverage-run-unittest

      - run: *run-cpp-tests

  #
  # windows
  #

  build-win:
    parameters:
      python-version:
        type: string
      python-arch:
        type: string

    executor:
      name: win/default

    steps:
      - checkout

      - ocean/nuget-install-python:
          python-arch: << parameters.python-arch >>
          python-version: << parameters.python-version >>

      - ocean/pip-install:
          requirements: requirements.txt
          cache: false

      - ocean/build-dist:
          dist-type: bdist_wheel
          dist-dir: ./distotheque

      - store_artifacts: *store-dist

      - persist_to_workspace: *persist-dist

  test-win:
    parameters:
      python-version:
        type: string
      python-arch:
        type: string

    executor:
      name: win/default

    steps:
      - checkout

      - ocean/nuget-install-python:
          python-arch: << parameters.python-arch >>
          python-version: << parameters.python-version >>

      - attach_workspace: *attach-dist

      - ocean/install-requirements

      - ocean/pip-install:
          args: --no-index --find-links=distotheque dwave-greedy

      - ocean/coverage-run-unittest

  #
  # docs
  #

  test-docs:
    docker:
      - image: circleci/python:3.7    # RtD uses py37

    steps:
      - checkout

      - attach_workspace: *attach-dist

      - ocean/install-requirements:
          requirements: requirements.txt tests/requirements.txt docs/requirements.txt

      - ocean/pip-install:
          args: --no-index --find-links=distotheque dwave-greedy

      - run:
          name: Build docs
          command: |
            . env/bin/activate
            make -C docs/ html

      - store_artifacts:
          path: ./docs/build/html

      - run:
          name: Test docs
          command: |
            . env/bin/activate
            make -C docs/ doctest

      - run:
          name: Test links
          command: |
            . env/bin/activate
            make -C docs/ linkcheck

  #
  # deploy package to PyPI
  #

  pypi-deploy:
    docker:
      - image: circleci/python:3.9

    steps:
      - attach_workspace: *attach-dist

      - run:
          name: Deploy sdist and wheels to PyPI
          command: |
            python -m venv env
            . env/bin/activate
            pip install twine
            twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --skip-existing ./distotheque/*


workflows:
  build-test-deploy:
    jobs:
      - build-sdist:
          filters: &always-run  # required because it's indirectly required by the deploy job that runs on tags only
            tags:
              only: /.*/

      - build-manylinux:
          name: build-<< matrix.manylinux-tag >>_<< matrix.manylinux-arch >>-py<< matrix.python-version >>
          matrix:
            parameters:
              manylinux-tag: ["manylinux1", "manylinux2014"]
              manylinux-arch: ["x86_64"]
              python-version: &python-versions ["3.6.8", "3.7.9", "3.8.9", "3.9.4"]
          filters:
            <<: *always-run

      - test-linux:
          name: test-linux-py<< matrix.python-version >>
          requires:
            - build-sdist
            - build-manylinux
          matrix:
            parameters:
              python-version: *python-versions
          filters:
            <<: *always-run

      - test-install:
          requires:
            - build-sdist
            - build-manylinux
          filters:
            <<: *always-run

      - test-docs:
          requires:
            - build-sdist
            - build-manylinux
          filters:
            <<: *always-run

      - build-macos:
          name: build-macos-py<< matrix.python-version >>
          matrix:
            parameters:
              python-version: *python-versions
          filters:
            <<: *always-run

      - test-macos:
          name: test-macos-py<< matrix.python-version >>
          requires:
            - build-sdist
            - build-macos
          matrix:
            parameters:
              python-version: *python-versions
          filters:
            <<: *always-run

      - build-win:
          name: build-win-<< matrix.python-arch >>-py<< matrix.python-version >>
          matrix:
            parameters:
              python-version: *python-versions
              python-arch: &python-archs-win ["", "x86"]
          filters:
            <<: *always-run

      - test-win:
          name: test-win-<< matrix.python-arch >>-py<< matrix.python-version >>
          requires:
            - build-win
          matrix:
            parameters:
              python-version: *python-versions
              python-arch: *python-archs-win
          filters:
            <<: *always-run

      - pypi-deploy:
          requires:
            - test-linux
            - test-macos
            - test-win
            - test-docs
            - test-install
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*((\.dev|rc)([0-9]+)?)?$/
            branches:
              ignore: /.*/
